### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ghost**
Good job on funding your kick-starter project btw

### CODE REVIEW

**Comment by ghost** [comment]
I added a logo for your great new app, I found you on kickstarter, love the idea, if you want to use the logo your free to sell it, whatever, I don't care, I made all of it but claim no copyright stuff. Hope you like it, there is a .sketch file so you can make changes. It follows a flat design, hope to contribute in the future :smile:

**Comment by ghost** [comment]
Oh and the logo, yeah I'm fine for you to use it but it might not go so well with Instagram if your a competing service, just saying. Oh and digital ocean is better and cheaper than parse. And you just use http requests so no fussing around with frameworks, simple!

**Comment by ColeHud** [comment]
Thanks! I'll look into it :)

**Comment by ColeHud** [comment]
I just ran it, and it looks amazing! Thanks so much. This is my second IOS app ever, so I still have a lot to learn

**Comment by ghost** [comment]
That's great,com happing to contribute more in the future, I'll let you get started so I have the basic idea of what the apps supposed to like like and function though before I help out any more. Also is InstaGrub going to support android?

**Comment by ColeHud** [comment]
Thanks! Eventually it will support Android. I actually have more Android dev experience, and I'm a lot better at Java. I'm mainly doing Instagrub to learn my way around IOS.

**Comment by ghost** [comment]
If you want me to help out with something create a new issue and assign me (@LOVE2CODE123)

**Comment by ColeHud** [comment]
Thanks!

**Comment by ghost** [comment]
Ok, well I'm similar, Instarted learning to code on a Linux so didn't get started learning iOS until my Linux compute died and I decided to buy a Mac.

**Comment by ColeHud** [comment]
I'm only better at Java because I'm taking AP Computer Science this year. I've lived on Mac pretty much my whole life.

**Comment by ghost** [comment]
Well I guess so that makes scene, if you need me to help you out on anything I'll make sure I comment my code really really well so you know exactly what's happening.

**Comment by ColeHud** [comment]
Thanks, I really appreciate it :)

**Comment by ghost** [comment]
Just wondering how is the app supposed to work?

**Comment by ColeHud** [comment]
Pretty much just like instagram. You take a picture of some food, apply a filter for that type of food (eg. a hotdog filter), and then you share it to instagrub. Followers who are subscribed to you will see your photos.

**Comment by ghost** [comment]
So is there something like well like or love?

**Comment by ColeHud** [comment]
yes, along with share to facebook, twitter, etc.

**Comment by ghost** [comment]
That's cool

**Pull request merged**
